version: '3.8'

services:
  # web:
  #   image: mcr.microsoft.com/dotnet/aspnet:8.0
  #   ports:
  #     - "8080:80"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #     - redis
  #     - rabbitmq
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
  #     - ConnectionStrings__DefaultConnection=${PostgresConnection}
  #     - Redis__ConnectionString=${RedisConnection}
  #     - RabbitMQ__ConnectionString=${RabbitMQConnection}

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  db-data:
  redis-data:
  rabbitmq-data:

